### ISSUE TITLE
Mod manager cannot find game path

### ISSUE THREAD

**Issue by Awrel** [Kaedrin/warhammer-mod-manager#27]
So when i start up the mod manager i get an error telling me it cannot find a game path and i dont know how to solve it i read the previous post but it says the 2 xml files i only have one named GameData and i dont know if im supposed to edit something there i would appreciate some help because the CA mod manager is noddy and doesnt work

**Comment by clasbin** [comment]
I am just a normal user, not associated with the development team, so what follows is just what I figured out for myself. Only apply if it makes sense to you. If not, ask again, provide more context and maybe we'll figure it out together.
1) 2nd xml should be generated after you successfully launch the mod manager and save a profile or launch a game. it's normal.
2) Reasons for not detecting your game could be non standard location (like custom steam library) or changing your drive letters or moving a game after it was previously located. Also, and this is very important, **you need to launch the game at least once after installing it through Steam**, let the additional setup take place, let the launcher start, (add a mod or not), launch the game, quit from the menu and only then start the mod manager and try to detect it.
- in GameData.xml look at the lines starting with < Game....
'< Game ExePath="D:\Games\SteamLibrary\steamapps\common\Total War Saga Thrones of Britannia" ExeName="ThronesofBritannia" AppDataGameName="ThronesofBritannia">712100</Game >'
- you are only interested in the ExePath parameter. if it is blank ("") for **all** games defined in the list, the program should try to detect the games location and fill the list;
- if, for whatever reason, one is not blank but contains an invalid path, then you get that error message. you can manually edit the path, save and launch again;
- deleting GameData.xml is just an easy way to reset the paths, mod_manager_settings_v2.xml contains default program settings which you won't need to change anyway and the last managed game, so that the program loads its profile automatically on the next run - no vital info that you cannot recover (profiles are stored separately);
- there is no need to actually delete them either, you can just rename them to whatever.xml.bak or something of the sort if you want to be sure you want to review or recover them later.

**Comment by Awrel** [comment]
So your method actually worked the mod manager is working now but i keep getting an error : Length cannot be less than zero.
Parameter name: length
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Warhammer2MM.FormMain.HandleContentFolder()
   at Warhammer2MM.FormMain.LoadPackFiles()
   at Warhammer2MM.FormMain.RefreshApp()
   at Warhammer2MM.FormMain.setGetFileData(String CheckBoxName)
   at Warhammer2MM.FormMain.warhammer2Game_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Warhammer2MM
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Linca%20Eugen/Desktop/Potato/Warhammer2MM.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3314.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Steamworks.NET
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.0
    CodeBase: file:///C:/Users/Linca%20Eugen/Desktop/Potato/Steamworks.NET.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Awrel** [comment]
Its for Warhammer 2 and i cannot continue none of my mods appear after i press continue , also i did a total reset of the game reinstalled it but i still get this error

**Comment by clasbin** [comment]
* back to the location of the xml files, is there a Profiles folder too? inside there should be a Warhammer 2 folder and some text documents listing your mods. try renaming them to something.txt.bak;
* I don't own Warhammer so don't know any particular problems with this game;
* anyway, if you are not using lots of mods with overlapping functions the CA manager should be enough, so try Revert to Vanilla and play your game while waiting for a new release.

**Comment by Awrel** [comment]
The profiles folder is empty

**Comment by Kaedrin** [comment]
SteamWorks is unable to find your Steam install. You are using Steam, correct?

**Comment by Kaedrin** [comment]
This is going to be closed in 1.8.3 in a few minutes.
